package network.common;

public enum CommandType {
	TAIKHOAN_GET_ALL,

	NHANVIEN_GET_ALL,

	KHUYENMAI_GET_ALL,
	KHUYENMAI_ADD,
	KHUYENMAI_UPDATE,
	KHUYENMAI_DELETE,
	KHUYENMAI_GET_BY_ID,
	KHUYENMAI_GENERATE_ID
}
