package network.common;

public enum CommandType {
    //TaiKhoan_Controller
    TAIKHOAN_GET_ALL,
    TAIKHOAN_UPDATE_PASSWORD,

    KHACHHANG_GET_ALL,
    KHACHHANG_ADD,
    KHACHHANG_UPDATE,

    HANGKHACHHANG_GET_ALL,

    NHANVIEN_GET_ALL,
    NHANVIEN_ADD_WITH_ACCOUNT,
    NHANVIEN_UPDATE,

    MONAN_FIND_BY_ID,
    MONAN_ADD,
    MONAN_UPDATE,
    MONAN_DELETE,
    MONAN_GET_ALL,
    BAN_GET_ALL,
    LOAIBAN_GET_ALL,
    BAN_UPDATE,

    DONDATBAN_GET_ALL,
    DONDATBAN_GET_BY_BAN,
    DONDATBAN_ADD,
    DONDATBAN_UPDATE,

    HOADON_GET_ALL,
    HOADON_GET_BY_MADATBAN,
    HOADON_ADD,
    HOADON_UPDATE,

    CTHD_GET_BY_MAHD,
    CTHD_ADD_BATCH,
    CTHD_DELETE_BY_MAHD,

    //ThongKeNV_Controller
    HOADON_GET_ALL_HOADON_NV_THEO_THANG,

    DONDATBAN_GET_ALL_DONDATBAN_NV_THEO_THANG,

    DONDATBAN_GET_KHACHHANG_THEO_THANG_NV_CUTHE,

    HOADON_GET_TONG_DOANHTHU_NV_THEO_THANG,

    HOADON_GET_DOANHTHU_NV_THEO_NAM,

    HOADON_GET_HOADON_NV_THEO_NAM,

    DONDATBAN_GET_ALL_DONDATBAN_THEO_NAM_NV_CUTHE,

    DONDATBAN_GET_KHACHHANG_THEO_NAM_NV_CUTHE,

    HOADON_GET_TONG_DOANHTHU_NV_THEO_NAM,

    DONDATBAN_COUNT_DONDATBAN_THEO_NAM_NV_CUTHE,

    //DashboardNV_Controller
    HOADON_GET_HOADON_NV_THEO_NGAY_CUTHE,
    DONDATBAN_GET_ALL_DONDATBAN_THEO_NGAY_NV_CUTHE,
    //DashboardNV_Controller

    DONDATBAN_GET_KHACHHANG_THEO_NGAY_NV_CUTHE,

    HOADON_GET_TONG_DOANHTHU_NV_THEO_NGAY_CUTHE,

    //ThongKeNVQL_Controller
    HOADON_GET_ALL_HOADON_THEO_THANG,

    DONDATBAN_GET_ALL_DONDATBAN_THEO_THANG,

    DONDATBAN_GET_KHACHHANG_THEO_THANG,

    HOADON_GET_TONG_DOANHTHU_THEO_THANG,

    DONDATBAN_COUNT_LOAIBAN_THEO_THANG,

    HOADON_GET_DOANHTHU_THEO_NAM,

    HOADON_GET_ALL_HOADON_THEO_NAM,

    DONDATBAN_GET_ALL_DONDATBAN_THEO_NAM,

    DONDATBAN_GET_KHACHHANG_THEO_NAM,

    HOADON_GET_TONG_DOANHTHU_THEO_NAM,

    DONDATBAN_COUNT_LOAIBAN_THEO_NAM,

    DONDATBAN_COUNT_DONDATBAN_THEO_NAM,

    //DashboardNVQL_Controller
    HOADON_GET_HOADON_THEO_NGAY_CUTHE,
    DONDATBAN_GET_ALL_DONDATBAN_THEO_NGAY_CUTHE,
    DONDATBAN_COUNT_LOAIBAN_THEO_NGAY_CUTHE,
    //DashboardNVQL_Controller

    DONDATBAN_GET_KHACHHANG_THEO_NGAY_CUTHE,

    HOADON_GET_TONG_DOANHTHU_THEO_NGAY_CUTHE,
    THONGKE_FINDBYID,

    //Gia An (không trùng tên với các constant phía trên)
    BAN_GET_ALL_ENTITY,
    BAN_ADD,
    BAN_DELETE,
    BAN_GENERATE_ID,

    MONAN_GENERATE_ID,

    CTHD_REPLACE_BY_MAHD,

    HOADON_UPDATE_PAYMENT,
    HOADON_UPDATE_STATUS,

    DONDATBAN_GET_KH_BY_MADATBAN,

    KHACHHANG_GET_BY_SDT,
    KHACHHANG_GET_BY_MA,
    KHACHHANG_UPDATE_DIEM,

    KHUYENMAI_GET_ALL,
    KHUYENMAI_ADD,
    KHUYENMAI_UPDATE,
    KHUYENMAI_DELETE,
    KHUYENMAI_GET_BY_ID,
    KHUYENMAI_GENERATE_ID
}
